Feat/public letter route
opengovsg/letters pull request #161
Opened 2023-06-23 08:20 UTC by gweiying

## Context

_Why does this PR exist? What problem are you trying to solve? What issue does this close?_

Closes [insert issue #]

## Approach

_How did you solve the problem?_

**Features**:

- Details ...

**Improvements**:

- Details ...

**Bug Fixes**:

- Details ...

## Before & After Screenshots

**BEFORE**:
[insert screenshot here]

**AFTER**:
[insert screenshot here]

## Tests

_What tests should be run to confirm functionality?_

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New environment variables**:

- `env var` : env var details

**New scripts**:

- `script` : script details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

## Risks

_Describes potential risks with this PR. Consider carefully what could possibly happen in a worse case scenario. If possible, try to define risks as 2 items: **Impact** and **Likelihood** and use your best judgment._

2023-06-23 09:49 UTC, AikoPath requested changes
Looks like this is breaking the existing 404 error handling handling.

2023-06-23 09:49 UTC, AikoPath commented on backend/src/core/utils/generate-public-id.spec.ts
> +    expect(id).toEqual('abcdefghi')
I am not sure if the comments here that explain what the code does are required.

2023-06-23 09:49 UTC, AikoPath commented on frontend/src/app/routes/public.routes.tsx
>  ]
This PR breaks the /error re-direct for paths with more than one path component (other than `/admin/`)
I suspect this is the part of the PR that causes this.

<img width="1005" alt="Screenshot 2023-06-23 at 5 32 05 PM" src="https://github.com/opengovsg/letters/assets/12240377/cc547963-537c-4ba4-93b1-9eecf8f8de23">
<img width="1006" alt="Screenshot 2023-06-23 at 5 27 54 PM" src="https://github.com/opengovsg/letters/assets/12240377/4527bdfc-bb12-4d02-9e1c-167b3eabd8fc">

2023-06-23 13:38 UTC, gweiying commented on frontend/src/app/routes/public.routes.tsx
>  ]
Good catch will look into it, thanks!

2023-06-26 02:53 UTC, gweiying commented on frontend/src/app/routes/public.routes.tsx
>  ]
Reverted in [b49f919](https://github.com/opengovsg/letters/pull/161/commits/b49f919e747c98a045a0fe00a003ad384dd81df8) and updated in [7ec58b7](https://github.com/opengovsg/letters/pull/161/commits/7ec58b77cc1252e059177bd23f24b83c89825098).

The change now causes the following behavior:
- if a person lands on [letters.gov.sg/](http://letters.gov.sg/)<invalid-letters-link>, we redirect them to [letters.gov.sg/error](http://letters.gov.sg/error)
- if a person lands on [letters.gov.sg/hello/there](http://letters.gov.sg/hello/there) (invalid link), we redirect them to [letters.gov.sg/error](http://letters.gov.sg/error)
- if a person lands on [letters.gov.sg/admin/hello](http://letters.gov.sg/admin/hello) (internal link), we redirect them to [letters.gov.sg/admin/login](http://letters.gov.sg/admin/login) if they're not logged in.

2023-06-26 07:39 UTC, gweiying commented on backend/src/core/utils/generate-public-id.spec.ts
> +    expect(id).toEqual('abcdefghi')
[d9d167c](https://github.com/opengovsg/letters/pull/161/commits/d9d167cacf7e95883c86580050a7102b1911a4a7)

2023-06-27 11:40 UTC, AikoPath approved these changes
LGTM

2023-06-27 23:49 UTC, merged