fix: csv uploads error UI
opengovsg/letters pull request #167
Opened 2023-06-30 05:59 UTC by PikkaPikkachu

## Context

We are trying to improve the design for CSV uploads. In this PR specifically we will group the errors for each row together, so that's it's easier for users to process these errors. 

Closes this notion [task](https://www.notion.so/opengov/Eng-Error-handling-for-CSV-uploads-47eb937d69274a03b4ae551446d16f4c).

## Approach

Fixed the design. Did some front-end processing to group errors from the same row together using `reduce`.
Since we don't expect a ton of errors anyways (the scale of errors would be limited by the number of letters generated in one go), front-end processing would still make sense and should not be too heavy.

**Features**:
- Group related row errors together

## Before & After Screenshots

**BEFORE**:

<img width="1511" alt="Screenshot 2023-06-30 at 1 57 44 PM" src="https://github.com/opengovsg/letters/assets/25703976/0928251e-093e-4d90-a847-f8f2d6ffc5c9">

**AFTER**:

https://github.com/opengovsg/letters/assets/25703976/c7b74b75-5664-4dd4-af7a-5d784db272ca

2023-07-01 05:41 UTC, AikoPath requested changes
Only two tiny naming suggestions. Otherwise lgtm!

FYI:
Your "after" video in the PR description briefly shows your slack window.
Given the open source nature of OGP it might be good to try to not include personal or internal information in our repos.

2023-07-01 05:41 UTC, AikoPath commented on frontend/src/features/issue/BulkIssueDrawer/UploadCsvErrorsTable.tsx
> +  const processedErrors = uploadCsvErrors.reduce(
Based on what the function is doing I'd recommend to name it something along the lines of `errorsGroupdByRow` or `errorsByRow`.

2023-07-01 05:41 UTC, AikoPath commented on frontend/src/features/issue/BulkIssueDrawer/UploadCsvErrorsTable.tsx
> +  const errorTableData = processedErrors.map((errorData, index) => {
This looks like it is mapping the raw data into actual table rows and returning them.
We could call it something like `errorTableRows`.

2023-07-03 02:48 UTC, PikkaPikkachu commented on frontend/src/features/issue/BulkIssueDrawer/UploadCsvErrorsTable.tsx
> +  const processedErrors = uploadCsvErrors.reduce(
Sounds good :)

2023-07-03 03:00 UTC, PikkaPikkachu commented
> Given the open source nature of OGP it might be good to try to not include personal or internal information in our repos.

Thanks! I removed the previous test video!

2023-07-03 03:44 UTC, AikoPath approved these changes

2023-07-03 04:11 UTC, merged