fix: routing for non excistent template id
opengovsg/letters pull request #221
Opened 2023-08-03 05:37 UTC by ddanelynn

## Context

Currently, when accessing a non-existent template id route, the frontend just stays on the issue letter dashboard page instead of throwing an error. 
Accessing the frontend route for issuing a non-existent template id, e.g. http://letters-stg.beta.gov.sg/admin/templates/100000/issue should redirect a user back to Templates dashboard.

Closes [this issue](https://www.notion.so/opengov/2ccadbea5c734aa09614b4ca8cc7177e?v=76cff9fca57b496f857c990e2639af2f&p=400b4197f04f44c9954e7bf801cf226b&pm=s).

## Approach
Add a `TemplateIdProtectedRoute` layer under `AdminProtectedRoute` to ensure template Id in url is valid.

**Issue**
There will be a 4-5s delay before page is redirected to /templates due to backend fetching speed (checking if the templateId exists).

https://github.com/opengovsg/letters/assets/66818697/67a1e5c4-8a9c-4445-b7a2-8c6ad6d927b1

2023-08-03 05:49 UTC, PikkaPikkachu reviewed
Overall LGTM, just a few suggestions :))

2023-08-03 05:49 UTC, PikkaPikkachu commented on frontend/src/features/TemplateIdProtectedRoute.tsx
> +  const templateId = +location.pathname.split('/')[3]
nit: did we try using this for fetching the template id? 
```
const { templateId } = useTemplateId()
```

2023-08-03 05:49 UTC, PikkaPikkachu commented on frontend/src/features/TemplateIdProtectedRoute.tsx
> +    <>
nit: I don't think we should need `<></>` here?

2023-08-03 07:56 UTC, gweiying commented
Took a quick look at the PR and happy to discuss further on this!

I'm not sure we would need a wrapping component `TemplateIdProtectedRoute` here instead of directly checking for the template's existence in `BulkIssuePage`. Off the top of my head, I'm actually not sure where else we would use this wrapper, so I would think that the simpler approach is preferable. What do you think?

2023-08-04 03:23 UTC, PikkaPikkachu commented on frontend/src/features/issue/BulkIssuePage.tsx
> +    // eslint-disable-next-line @typescript-eslint/unbound-method
nit: what's this es-lint comment ignoring 😅 ?

2023-08-04 03:24 UTC, PikkaPikkachu commented
Honestly, I wouldn't mind having the template validation check to be a separate component (like we had before), since `BulkIssuePage` component is pretty big in itself, so we could actually have a separate parent component, but not have it at the router level, instead at `BulkIssuePage` level — overall I think this is okay too though :)

LGTM! Thanks for the quick iterations! :D

2023-08-04 03:26 UTC, ddanelynn commented on frontend/src/features/issue/BulkIssuePage.tsx
> +    // eslint-disable-next-line @typescript-eslint/unbound-method
oops

2023-08-04 03:27 UTC, ddanelynn commented on frontend/src/features/TemplateIdProtectedRoute.tsx
> +  }, [template, navigate, isTemplatesLoading])
I think there is no error returns from the hook, not super sure how to use it :000

2023-08-04 03:28 UTC, ddanelynn commented on frontend/src/features/TemplateIdProtectedRoute.tsx
> +    <>
Tried to delete but it gave me red lines. I think need a wrapper for conditional returns

2023-08-04 07:45 UTC, PikkaPikkachu commented on frontend/src/features/TemplateIdProtectedRoute.tsx
> +  }, [template, navigate, isTemplatesLoading])
const { template } = useGetTemplateById(templateId)
if (error) {
  return <Navigate to={`/templates`} />
}
try this?

2023-08-04 07:47 UTC, PikkaPikkachu commented on frontend/src/features/TemplateIdProtectedRoute.tsx
> +  }, [template, navigate, isTemplatesLoading])
Ahh there's no error being returned by the hook.

2023-08-04 07:49 UTC, PikkaPikkachu commented on frontend/src/features/issue/BulkIssuePage.tsx
> +  }, [template, navigate, isTemplatesLoading])
do we need to have `navigate` as a dependency in the `useEffect`?

2023-08-04 07:51 UTC, PikkaPikkachu approved these changes
LGTM! Can we also check that the templates with existing or valid IDs are routed to correct, the test plan does not have a screen recording for that — so just wanted to make sure, we tested both the cases :)

2023-08-04 08:08 UTC, gweiying commented on frontend/src/features/TemplateIdProtectedRoute.tsx
> +  }, [template, navigate, isTemplatesLoading])
Hey all, what do you think about modifying the `useGetTemplateById` hook here in `templates.hooks.ts` which would prevent us from relying on this `useEffect` workaround instead? This is a common design pattern for React Query hooks, so we should lean into it and use the exposed error instead of using the `useEffect` which can cause some unnecesary rerenders on the page. 

We also do the same logic in `useGetLetterByPublicId`

```
export const useGetTemplateById = (templateId: number) => {
  const { data, isLoading, error } = useQuery(['templates', templateId], () =>
    api.url(`/templates/${templateId}`).get().json<GetTemplateDto>(),
  )

  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  return { template: data!, isTemplateLoading: isLoading, error }
}
```

2023-08-04 08:12 UTC, gweiying requested changes
Hey Dannelyn! I think you're on the right track with this loading spinner, if you're interested you can also check our react suspense to see how to do this elegantly, but I don't think it's necessary for now otherwise. 

I'm not so sure about using this useEffect and useState to handle the `isTemplateValid` logic, because `useEffect` often causes alot of unnecessary rerenders on the frontend that can cause the application to be non-performant. Since we can just use the returned errors from the `react-query` component to conditionally redirect, we should just use that error instead of engineering a new workaround. Let's chat on Monday if it's unclear so far!

2023-08-08 00:58 UTC, gweiying commented on frontend/src/features/issue/BulkIssuePage.tsx
> +  }
hey @ddanelynn, just wondering why we chose to handle the error and the navigation separately? are there different cases that `error` and `!isTemplatesLoading && !template` are returning?

2023-08-08 06:09 UTC, ddanelynn commented on frontend/src/features/issue/BulkIssuePage.tsx
> +  }
ah make sense

2023-08-08 06:31 UTC, gweiying commented on frontend/src/features/issue/hooks/templates.hooks.ts
> +  const { data, isLoading, error } = useQuery(['templates', templateId], () =>
Just tested it out locally, we might also want to add a `retry: false` here ([see docs](https://tanstack.com/query/v4/docs/react/reference/useQuery)). The spinner is loading for a long time, and that's probably because the query is retrying a few times before failing.

2023-08-08 07:09 UTC, gweiying approved these changes
lgtm! behaves beautifully, thanks for the change

2023-08-08 07:19 UTC, merged