Feat: detailed dashboard view UI
opengovsg/letters pull request #237
Opened 2023-08-11 06:02 UTC by PikkaPikkachu

## Context

Build a detailed dashboard view of the batch letters for the new UI revamp, as in the figma [here](https://www.figma.com/file/KVFsGATLUfvPqKE2lY9niH/LetterSG?node-id=1634%3A55391&mode=dev). 

## Approach

1. Build new components for the detailed batch view page. 
2. We also remove the old components that not being used anymore. 
3. This is mostly a frontend change, with a bit of change in the dto objects for further compatibility and reducing code base's complexity. 

**Features**:

1. When users click on the batch, they are redirected to the detailed batch letters page. 
2. They are shows certain stats about the batch. 
3. Officers can see the individuals letters that they issued and click on any of the rows to open a drawer for more information on the letters. 

## Before & After Screenshots

**AFTER**:

https://github.com/opengovsg/letters/assets/25703976/047e1332-c815-485c-9f5c-46d3bfef67f3

2023-08-15 01:04 UTC, gweiying commented on backend/src/core/dto-mappers/letter.dto-mapper.ts
> +      ? letter.notifications[0].recipient
suggestion, would be good to leave a comment here why we're returning the recipient from the first notification as a workaround!

2023-08-15 01:11 UTC, gweiying commented on frontend/src/features/dashboard/hooks/dashboard.hooks.ts
> +  const { data, isLoading } = useQuery(['batches'], () =>
nit, we would probably want to use a different query key here, perhaps `['batch', batchId]`, to make full use of the caching logic. using `['batches']` as a query key here will override the cache in `useGetBatches`!

2023-08-15 01:26 UTC, gweiying commented on backend/src/batches/batches.service.ts
> +      },
See comment above about fetching `template` twice!

2023-08-15 01:49 UTC, gweiying commented on backend/src/database/migrations/1691859222806-update-is-password-protected-and-notification-channel-columns-in-batches.ts
> +  }
the migration scripts themselves look ok to me, but just wanna think about performance of the backfill migration. would be good to practice on staging and have a plan for the following:
- backup 
- monitor performance of migration (RDS CPU utilization, IOPs etc)
- checking that columns are filled correctly after migration

If the performance is poor on staging we might need to consider running the next release at an offpeak time or batching the backfill

2023-08-15 01:53 UTC, gweiying commented on frontend/src/features/dashboard/components/DownloadCsvButton.tsx
> +export const DownloadCsvButton = ({
nice component!

2023-08-15 01:57 UTC, gweiying commented on frontend/src/features/dashboard/hooks/dashboard.hooks.ts
> +export const useGetBatchData = (batchId: number) => {
tiny nit, non-blocking. what do you think about renaming this to `useGetBatchById` for consistency with other hooks?

2023-08-15 02:02 UTC, gweiying commented on frontend/src/features/dashboard/components/batchViewComponents/IssuedBatchView.tsx
> +  if (!batch) {
Might need to add a check here for whether the batch is still loading, e.g. `if (!batch && !isBatchLoading) { ... }` 

I had some weird behavior locally where it showed the `ErrorPage` for a second before the batch loaded. If it's loading, we might need a loading state instead of `IssuedBatchViewLetterTable`.

Also, wondering what the ideal behavior should be, should we redirect the user back to `/admin/letters`, redirect the user to `/error`, or just display the `<ErrorPage />`? I would prefer the first, redirecting them back automatically `letters` as they should only reach this page if the batch id doesn't exist, but I don't have a strong preference here. What do you think?

2023-08-15 02:07 UTC, gweiying requested changes
Did one pass to review the files so far, and mostly looks good to me! Left some small nits on cleanup as well as query/fetch performance on both frontend and backend

2023-08-15 02:59 UTC, PikkaPikkachu commented on frontend/src/features/dashboard/components/batchViewComponents/IssuedBatchView.tsx
> +  if (!batch) {
I think either way is fine for me — I think I have come across both behaviours of websites :
1. "Oops, 404, page not found" or something?
2. Where there is a automatic redirection

Sometimes I think redirection can be confusing, because I would try to access the same URL again, in hopes that it would lead me to the correct page, but an error page, shows that this thing doesn't exist and I wouldn't try again. 

But again neutral to either ways [+ seems like a rare case for now]. 

So let's just go with redirection then ?

2023-08-15 06:51 UTC, PikkaPikkachu commented on frontend/src/features/dashboard/components/batchViewComponents/IssuedBatchView.tsx
> +  if (!batch) {
As discussed offline, we will stick to redirection, since that's what we are using across the website for admin access!

2023-08-15 08:25 UTC, PikkaPikkachu commented
Thank you @gweiying for the review, have addressed the suggestions you proposed and as discussed offline, the DB/CPU performance seemed fine during our first staging deployment.

2023-08-16 03:44 UTC, gweiying approved these changes
lgtm~ thanks for the quick fixes

2023-08-16 04:59 UTC, gweiying commented on frontend/src/features/dashboard/components/batchViewComponents/IssuedBatchView.tsx
> +export const IssuedBatchView = (): JSX.Element => {
up for discussion, what do you think of moving this file out to `~features/dashboard` since it's a page view (no longer a component)?

2023-08-16 06:23 UTC, PikkaPikkachu commented on frontend/src/features/dashboard/components/batchViewComponents/IssuedBatchView.tsx
> +export const IssuedBatchView = (): JSX.Element => {
changed [here](https://github.com/opengovsg/letters/pull/237/commits/e229033d7cc65dc30d920fe7cb855257ab10f961), thanks!

2023-08-16 06:34 UTC, merged