chore: admin query keys
opengovsg/letters pull request #260
Opened 2023-08-23 07:51 UTC by disKeith

## Context

_Why does this PR exist? What problem are you trying to solve? What issue does this close?_

Closes [insert issue #]

## Approach

_How did you solve the problem?_

**Features**:

- Details ...

**Improvements**:

- Details ...

**Bug Fixes**:

- Details ...

## Before & After Screenshots

**BEFORE**:
[insert screenshot here]

**AFTER**:
[insert screenshot here]

## Tests

_What tests should be run to confirm functionality?_

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New environment variables**:

- `env var` : env var details

**New scripts**:

- `script` : script details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

## Risks

_Describes potential risks with this PR. Consider carefully what could possibly happen in a worse case scenario. If possible, try to define risks as 2 items: **Impact** and **Likelihood** and use your best judgment._

2023-08-24 02:24 UTC, gweiying commented on frontend/src/constants/query-keys.ts
> +    [adminQueryKeys.template, templateId] as const,
what do you think of something like the following instead:
```
export const adminQueryKeys = {
  templates: (templateId?: number) => templateId ? ['templates', templateId] : ['templates']
}
```

2023-08-24 02:36 UTC, gweiying requested changes
I found an article [here](https://tkdodo.eu/blog/effective-react-query-keys#structure) that might actually help inform our `queryKey` structuring abit better!
 
Thinking that the approach suggested in the blog above would be quite useful especially for batches, because we actually have batches - pagination and batches - item view.

2023-08-24 08:49 UTC, disKeith commented on frontend/src/constants/query-keys.ts
> +    [adminQueryKeys.template, templateId] as const,
thanks, that looks better - updated in https://github.com/opengovsg/letters/pull/260/commits/2b6e177fbd3c81f8542dccc2d0dcc852e98c3c84 with new structure

2023-08-28 01:42 UTC, gweiying commented on frontend/src/constants/query-keys.ts
> +  batches: (type?: 'detail' | 'paginate', idOrOffset?: number) => {
Small suggestion. 

For the pagination, we will need 2 values, limit and offset. Thinking that we possibly accept an object here instead, for example`batches: ({ batchId, limit, offset })`, with a switch case on whether `limit` & `offset` are defined, or whether `batchId` is defined, or none of the above? This would mean that for a person using the function, they could just call it simply by passing `adminQueryKeys.batches({limit: 10, offset:10 })` for example without needing to look up what `type` refers to.

2023-08-29 03:53 UTC, disKeith commented on frontend/src/constants/query-keys.ts
> +  batches: (type?: 'detail' | 'paginate', idOrOffset?: number) => {
roger, updated in https://github.com/opengovsg/letters/pull/260/commits/f980729c10f1e06b7c7ed58dcb69f6b53d4cac36

2023-08-29 06:46 UTC, gweiying commented on frontend/src/constants/query-keys.ts
> +  who_am_i: 'who-am-i' as const,
sorry, final nit from me! can we use camelCase here?

2023-08-30 00:51 UTC, gweiying commented on frontend/src/constants/query-keys.ts
> +  }) => {
is it also possible to make this whole object optional? that way if no object is passed e.g. `batches()` it would directly return `['batches']`

2023-08-30 02:23 UTC, disKeith commented on frontend/src/constants/query-keys.ts
> +  }) => {
addressed comments in https://github.com/opengovsg/letters/pull/260/commits/5a22949238237db312d0031513aa48ae7c947282 !

2023-09-05 01:34 UTC, gweiying approved these changes
Overall looks good, can we push to staging to test out and verify that all queries are being cached/ invalidated correctly before merging? Can try React Query dev mode tool to help with profiling this

2023-09-07 05:34 UTC, merged