Feat/backend/access control
opengovsg/letters pull request #295
Opened 2023-09-18 09:10 UTC by disKeith

## Context

_Why does this PR exist? What problem are you trying to solve? What issue does this close?_

Closes [insert issue #]

## Approach

_How did you solve the problem?_

**Features**:

- Details ...

**Improvements**:

- Details ...

**Bug Fixes**:

- Details ...

## Before & After Screenshots

**BEFORE**:
[insert screenshot here]

**AFTER**:
[insert screenshot here]

## Tests

_What tests should be run to confirm functionality?_

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New environment variables**:

- `env var` : env var details

**New scripts**:

- `script` : script details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

## Risks

_Describes potential risks with this PR. Consider carefully what could possibly happen in a worse case scenario. If possible, try to define risks as 2 items: **Impact** and **Likelihood** and use your best judgment._

2023-09-21 04:31 UTC, disKeith commented on backend/src/access-control/access-control.service.ts
> +    })
tried using the `order` option within the `find` method didn't work for me as the column we want to sort by (`template.createdAt`) is not assignable to the entity's type:

```
const accessList = await this.accessControlRepository.find({
      where: {
        userId: userId,
      },
      relations: {
        template: true,
      },
      order: {
        'template.createdAt': 'DESC',
      },
    })
```

here's a working solution by explicity defining the query:

```
const accessList = await this.accessControlRepository
      .createQueryBuilder('access')
      .leftJoinAndSelect('access.template', 'template')
      .where('access.userId = :userId', { userId: userId })
      .orderBy('template.createdAt', 'DESC')
      .getMany()
```

wdyt?

2023-09-21 04:31 UTC, disKeith commented on backend/src/templates/templates.service.ts
> +      return +new Date(b.createdAt) - +new Date(a.createdAt)
https://github.com/opengovsg/letters/pull/295#discussion_r1332433408

2023-09-21 04:31 UTC, disKeith commented on backend/src/access-control/access-control.service.ts
> +    }
hmm let me see if i understood you correctly, the `createAccess` function is directly called only when we create a new template in which case we shouldn't be faced with the scenario where we might add duplicated pairings, in contrast to `addAccess` which should check for existing records as it might be called with an existing pairing in the table

2023-09-21 04:35 UTC, disKeith commented on backend/src/access-control/access-control.service.ts
> +        `user with email ${userEmailToInvite} not found`,
seems okay to me, since the `email` column is decorated with `@IsGovSgEmail`

2023-09-21 04:36 UTC, disKeith commented on backend/src/access-control/access-control.service.ts
> +    })
oh yes you're right! thanks for pointing this out~ https://github.com/opengovsg/letters/pull/295/commits/a6c7d11231fcbb97ebf988dd639d091d7c01a760

2023-09-21 04:36 UTC, disKeith commented on backend/src/access-control/access-control.service.ts
> +        user: true,
right, that's redundant, updated! https://github.com/opengovsg/letters/pull/295/commits/a6c7d11231fcbb97ebf988dd639d091d7c01a760

2023-09-21 04:37 UTC, disKeith commented on backend/src/access-control/access-control.service.ts
> +    const accessExists = await this.accessControlRepository.findOne({
ooh great find! updated with this change https://github.com/opengovsg/letters/pull/295/commits/a6c7d11231fcbb97ebf988dd639d091d7c01a760

2023-09-21 04:37 UTC, disKeith commented on backend/src/access-control/access-control.service.ts
> +    return false
neat! https://github.com/opengovsg/letters/pull/295/commits/a6c7d11231fcbb97ebf988dd639d091d7c01a760

2023-09-25 05:44 UTC, gweiying commented on backend/src/templates/templates.service.ts
> +    })
Small issue here, I think you'll find that your transaction isn't working as expected. You must be using the `transactionalEntityManager` exposed by the `dataSource.transaction` wrapper to save the entities, e.g.
```
return await this.dataSource.transaction(async (transactionalEntityManager) => {
// code to save here e.g. this.accessControlService.createAccessWithTransaction(userId, createdTemplate.id, transactionalEntityManager)
...code to save template
}
```



Above we're still using the global entity manager, so I think the transaction will not work as expected. Can see [here](https://orkhan.gitbook.io/typeorm/docs/transactions#creating-and-using-transactions) for more details on usage

2023-09-25 05:45 UTC, gweiying commented on backend/src/templates/templates.service.ts
> +    return null
why not directly throw an error here?

2023-09-25 05:47 UTC, gweiying commented on backend/src/access-control/access-control.service.ts
> +      const accessList = await this.templatesRepository.find()
small nit, but access control service shouldn't be using the templates repository directly - would be probably preferable to call template service instead!

2023-09-25 05:50 UTC, gweiying commented on backend/src/access-control/access-control.service.ts
> +    })
small nit, but access control service shouldn't be using the users repository directly - would be probably preferable to call auth service instead

2023-09-25 05:51 UTC, gweiying commented on backend/src/access-control/access-control.service.ts
> +    })
small nit, but access control service shouldn't be using the templates repository directly - would be probably preferable to call template service instead!

2023-09-25 06:01 UTC, gweiying requested changes
left some minor nits, might need to look specifically at the transaction manager

2023-09-26 05:10 UTC, disKeith commented
> left some minor nits, might need to look specifically at the transaction manager

addressed fixes for the comments in https://github.com/opengovsg/letters/pull/295/commits/50656ffa22c1f969d5285f594227af3f59f49e5f

from our offline discussion, have updated the logic flow for access control to be called only from `TemplatesService` and moved the endpoint for the add access function to be called from `TemplatesController` instead (via `{{host}}/id/invite`) with body `{"userEmail": "email-string"}`

2023-09-26 07:40 UTC, disKeith commented on backend/src/templates/templates.service.ts
> +      )
ah yes indeed thanks! moved in https://github.com/opengovsg/letters/pull/295/commits/455eb69fe693451e3c11fb2158fbf595ce804a37

2023-09-26 08:53 UTC, gweiying commented on backend/src/templates/templates.service.ts
> +      : await this.repository.find({
minor nit, maybe add a comment here why this would be null!

2023-09-26 08:55 UTC, gweiying commented on backend/src/access-control/access-control.service.ts
> +  }
can we subsume this function into add access so it's not accidentally used for now? so there'll only be createWithTransaction (used on template creation) and addAccess (used for template invitation)

2023-09-26 09:00 UTC, gweiying approved these changes
lgtm! works great, left inline suggestions on documentation or minor cleanups but performs beautifully!

2023-09-26 11:33 UTC, disKeith commented on backend/src/access-control/access-control.service.ts
> +  }
sounds good! updated in https://github.com/opengovsg/letters/pull/295/commits/472cd10c018dfe6bca50bb3d82ec297c868924dc

2023-10-02 07:28 UTC, closed without merging